#!/usr/bin/env bash

set -e

echo -n "This script will install utility packages and write on your .bashrc. Do you want to continue (y/n)? "
read answer

if [ "$answer" != "${answer#[Nn]}" ] ;
    then
        exit
fi

# Install PlatformIo
python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
echo "PATH=\"\$PATH:\$HOME/.platformio/penv/bin\"" >> $HOME/.bashrc

sudo apt install -y python3-pyudev libusb-dev

wget https://www.pjrc.com/teensy/00-teensy.rules
sudo cp 00-teensy.rules /etc/udev/rules.d/

echo "Installation complete! Run the following to update the changes made:"
echo "source ~/.bashrc"
